global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'stockify-services'
    static_configs:
      - targets: 
        - 'ingestion-service:8000'
        - 'stream-processor:8000'
        - 'storage-service:8000'
        - 'realtime-service:8000'
        - 'gateway-service:8000'
